# Generated by Django 5.0.6 on 2024-06-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=256)),
                ('max_capacity', models.IntegerField()),
                ('passes_generated', models.IntegerField()),
                ('image', models.URLField(default='https://darkroomphotos.com/wp-content/uploads/2021/10/image-file-formats-header-1-1-678x381@2x.png')),
                ('calendar_url', models.URLField(default='#')),
                ('booking_required', models.BooleanField(default=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('slots_required', models.BooleanField(default=False)),
                ('booking_complete', models.BooleanField(default=False)),
                ('slot_id', models.CharField(default='lmao', max_length=16)),
            ],
        ),
    ]
