# Generated by Django 5.0.6 on 2024-06-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='is_booking',
            new_name='is_booking_open',
        ),
    ]
