# Generated by Django 5.0.6 on 2024-07-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_is_booking_events_is_booking_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='is_booking_open',
            new_name='is_booking',
        ),
        migrations.AddField(
            model_name='events',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
