# Generated by Django 5.0.6 on 2024-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_is_booking_open_events_is_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='events',
            name='available_tickets',
            field=models.IntegerField(blank=True, default=350),
        ),
    ]
