# Generated by Django 5.0.6 on 2024-08-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=256)),
                ('available_tickets', models.IntegerField(blank=True, default=350)),
                ('passes_generated', models.IntegerField()),
                ('image', models.URLField(default='https://darkroomphotos.com/wp-content/uploads/2021/10/image-file-formats-header-1-1-678x381@2x.png')),
                ('calendar_url', models.URLField(default='#')),
                ('booking_required', models.BooleanField(default=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('slots_required', models.BooleanField(default=False)),
                ('booking_complete', models.BooleanField(default=False)),
                ('slot_id', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False, verbose_name='is_booked')),
                ('is_scanned', models.BooleanField(default=False, verbose_name='is_scanned')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='events.events')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secured_passes', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_passes', to='events.events', to_field='slot_id')),
            ],
        ),
    ]
