# Generated by Django 5.0.6 on 2024-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secure_id',
            field=models.CharField(blank=True, primary_key=True, serialize=False),
        ),
    ]
