# Generated by Django 5.0.6 on 2024-06-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
