# Generated by Django 5.0.6 on 2024-07-13 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_scanned',
        ),
        migrations.AddField(
            model_name='user',
            name='hood_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, max_length=50, size=None),
        ),
    ]
