# Generated by Django 5.0.6 on 2024-07-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_last_scanned_user_hood_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hood_points',
        ),
    ]
