# Generated by Django 5.0.6 on 2024-07-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_hood_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_scanned',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
