# Generated by Django 5.0.6 on 2024-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_tickets',
            field=models.IntegerField(blank=True, default=350),
        ),
    ]
