# Generated by Django 5.0.6 on 2024-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_available_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_tickets',
        ),
    ]
