# Generated by Django 5.0.6 on 2024-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_user_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_image',
            field=models.URLField(blank=True),
        ),
    ]
