# Generated by Django 5.0.6 on 2024-07-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('member_count', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('is_booking', models.BooleanField(default=True)),
            ],
        ),
    ]
