# Generated by Django 5.0.6 on 2024-08-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoods',
            name='is_booking',
        ),
    ]
